var tree = [["[Global Namespace]",,"",
                [["SplClassLoader","SplClassLoader.html","",
                [        ]]        ]],["I18n","I18n.html","",
                [["Generator","I18n\/Generator.html","",
                [["Csv","I18n\/Generator\/Csv.html","",
                [        ]]        ]],["Twig","I18n\/Twig.html","",
                [["I18nExtension","I18n\/Twig\/I18nExtension.html"," < Twig_Extension",
                [        ]],["PluralizeNode","I18n\/Twig\/PluralizeNode.html"," < Twig_Node",
                [        ]],["PluralizeTokenParser","I18n\/Twig\/PluralizeTokenParser.html"," < Twig_TokenParser",
                [        ]],["TranslateNode","I18n\/Twig\/TranslateNode.html"," < Twig_Node",
                [        ]],["TranslateTokenParser","I18n\/Twig\/TranslateTokenParser.html"," < Twig_TokenParser",
                [        ]]        ]],["Generator","I18n\/Generator.html","",
                [        ]],["GeneratorInterface","I18n\/GeneratorInterface.html","",
                [        ]],["I18n","I18n\/I18n.html"," < AbstractSingleton",
                [        ]],["I18nException","I18n\/I18nException.html"," < Exception",
                [        ]],["I18nInvalidArgumentException","I18n\/I18nInvalidArgumentException.html"," < InvalidArgumentException",
                [        ]],["I18nRuntimeException","I18n\/I18nRuntimeException.html"," < RuntimeException",
                [        ]],["Iana","I18n\/Iana.html","",
                [        ]],["Loader","I18n\/Loader.html"," < AbstractOptionable",
                [        ]]        ]]        ]

